-- Issue #20: canonical auction property references, immutable resolution
-- evidence, source and WGS84 geometry, and indexed viewport reads.

CREATE TABLE parcel_identities (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ko_code                     TEXT NOT NULL CHECK (ko_code = btrim(ko_code) AND ko_code <> ''),
    canonical_parcel_number     TEXT NOT NULL
                                CHECK (
                                    canonical_parcel_number = btrim(canonical_parcel_number)
                                    AND canonical_parcel_number <> ''
                                ),
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_parcel_identity UNIQUE (ko_code, canonical_parcel_number),
    CONSTRAINT uq_parcel_identity_complete UNIQUE (id, ko_code, canonical_parcel_number)
);

CREATE TABLE property_references (
    id                          UUID PRIMARY KEY,
    auction_id                  BIGINT NOT NULL REFERENCES auctions(id) ON DELETE RESTRICT,
    reference_order             INTEGER NOT NULL CHECK (reference_order >= 0),
    reference_type              VARCHAR(32) NOT NULL
                                CHECK (reference_type IN (
                                    'STRUCTURED_LOCATION', 'PARCEL', 'ADDRESS', 'STREET',
                                    'LAND_REGISTER', 'OTHER'
                                )),
    raw_ko                      TEXT,
    normalized_ko               TEXT,
    ko_code                     TEXT,
    raw_parcel_number           TEXT,
    canonical_parcel_number     TEXT,
    parcel_identity_id          BIGINT,
    land_register_number        TEXT,
    address_municipality        TEXT,
    address_settlement          TEXT,
    address_street              TEXT,
    address_house_number        TEXT,
    source_field                TEXT NOT NULL CHECK (btrim(source_field) <> ''),
    source_offset_start         INTEGER CHECK (source_offset_start IS NULL OR source_offset_start >= 0),
    source_offset_end           INTEGER CHECK (source_offset_end IS NULL OR source_offset_end >= 0),
    raw_evidence                TEXT,
    parser_version              TEXT NOT NULL CHECK (btrim(parser_version) <> ''),
    extraction_status           VARCHAR(32) NOT NULL
                                CHECK (extraction_status IN (
                                    'EXTRACTED', 'NO_STRUCTURED_REFERENCE', 'NEEDS_REVIEW',
                                    'USER_CONFIRMED', 'INVALID'
                                )),
    canonical_key               TEXT NOT NULL CHECK (btrim(canonical_key) <> ''),
    user_reviewed               BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_property_reference_key UNIQUE (auction_id, parser_version, canonical_key),
    CONSTRAINT uq_property_reference_order UNIQUE (auction_id, parser_version, reference_order),
    CONSTRAINT ck_property_reference_offsets CHECK (
        (source_offset_start IS NULL AND source_offset_end IS NULL)
        OR (
            source_offset_start IS NOT NULL
            AND source_offset_end IS NOT NULL
            AND source_offset_end >= source_offset_start
        )
    ),
    CONSTRAINT ck_property_reference_parcel_identity CHECK (
        parcel_identity_id IS NULL
        OR (ko_code IS NOT NULL AND canonical_parcel_number IS NOT NULL)
    ),
    CONSTRAINT fk_property_reference_parcel_identity
        FOREIGN KEY (parcel_identity_id, ko_code, canonical_parcel_number)
        REFERENCES parcel_identities (id, ko_code, canonical_parcel_number)
        ON DELETE RESTRICT
);

CREATE INDEX idx_property_references_auction
    ON property_references (auction_id, reference_order, canonical_key);
CREATE INDEX idx_property_references_parcel_identity
    ON property_references (parcel_identity_id)
    WHERE parcel_identity_id IS NOT NULL;

CREATE TABLE spatial_resolution_geometries (
    id                          UUID PRIMARY KEY,
    source_geometry             geometry NOT NULL,
    source_crs_authority        VARCHAR(16) NOT NULL CHECK (btrim(source_crs_authority) <> ''),
    source_crs_code             INTEGER NOT NULL CHECK (source_crs_code > 0),
    source_crs_definition       TEXT,
    canonical_geometry          geometry(Geometry, 4326) NOT NULL,
    original_geometry_valid     BOOLEAN NOT NULL,
    make_valid_applied          BOOLEAN NOT NULL DEFAULT FALSE,
    make_valid_reason           TEXT,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_spatial_source_srid CHECK (ST_SRID(source_geometry) = source_crs_code),
    CONSTRAINT ck_spatial_source_type CHECK (
        GeometryType(source_geometry) IN ('POINT', 'POLYGON', 'MULTIPOLYGON')
    ),
    CONSTRAINT ck_spatial_canonical_type CHECK (
        GeometryType(canonical_geometry) IN ('POINT', 'POLYGON', 'MULTIPOLYGON')
    ),
    CONSTRAINT ck_spatial_two_dimensions CHECK (
        ST_NDims(source_geometry) = 2 AND ST_NDims(canonical_geometry) = 2
    ),
    CONSTRAINT ck_spatial_non_empty CHECK (
        NOT ST_IsEmpty(source_geometry) AND NOT ST_IsEmpty(canonical_geometry)
    ),
    CONSTRAINT ck_spatial_source_validity_recorded CHECK (
        original_geometry_valid = ST_IsValid(source_geometry)
    ),
    CONSTRAINT ck_spatial_make_valid_evidence CHECK (
        (
            NOT make_valid_applied
            AND original_geometry_valid
            AND make_valid_reason IS NULL
        )
        OR (
            make_valid_applied
            AND NOT original_geometry_valid
            AND make_valid_reason IS NOT NULL
            AND btrim(make_valid_reason) <> ''
        )
    ),
    CONSTRAINT ck_spatial_canonical_valid CHECK (ST_IsValid(canonical_geometry)),
    CONSTRAINT ck_spatial_canonical_bounds CHECK (
        ST_XMin(Box3D(canonical_geometry)) >= -180
        AND ST_XMax(Box3D(canonical_geometry)) <= 180
        AND ST_YMin(Box3D(canonical_geometry)) >= -90
        AND ST_YMax(Box3D(canonical_geometry)) <= 90
    )
);

-- Derive rather than trust caller-supplied WGS84. Unlike a CHECK constraint,
-- this trigger is emitted by pg_dump in the post-data section, after COPY has
-- restored the stored canonical coordinates. A restore onto a different PROJ
-- version therefore does not re-transform historical source geometry.
CREATE OR REPLACE FUNCTION derive_canonical_resolution_geometry()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.canonical_geometry := ST_Transform(
        CASE
            WHEN NEW.make_valid_applied THEN ST_MakeValid(NEW.source_geometry)
            ELSE NEW.source_geometry
        END,
        4326
    );
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_spatial_resolution_geometry_derive_canonical
    BEFORE INSERT OR UPDATE OF source_geometry, source_crs_code,
        make_valid_applied, canonical_geometry
    ON spatial_resolution_geometries
    FOR EACH ROW EXECUTE FUNCTION derive_canonical_resolution_geometry();

CREATE INDEX idx_spatial_resolution_geometries_canonical
    ON spatial_resolution_geometries USING GIST (canonical_geometry);

CREATE TABLE location_resolution_cache_records (
    id                          UUID PRIMARY KEY,
    resolver                    TEXT NOT NULL CHECK (btrim(resolver) <> ''),
    resolver_version            TEXT NOT NULL CHECK (btrim(resolver_version) <> ''),
    input_fingerprint           CHAR(64) NOT NULL CHECK (input_fingerprint ~ '^[0-9a-f]{64}$'),
    source_dataset              TEXT NOT NULL CHECK (btrim(source_dataset) <> ''),
    source_dataset_version      TEXT NOT NULL CHECK (btrim(source_dataset_version) <> ''),
    source_dataset_sha256       CHAR(64) NOT NULL CHECK (source_dataset_sha256 ~ '^[0-9a-f]{64}$'),
    source_feature_id           TEXT,
    resolution_status           VARCHAR(16) NOT NULL
                                CHECK (resolution_status IN (
                                    'RESOLVED', 'NONE', 'NOT_FOUND', 'AMBIGUOUS', 'INVALID'
                                )),
    location_precision          VARCHAR(32) NOT NULL
                                CHECK (location_precision IN (
                                    'PARCEL', 'ADDRESS', 'STREET', 'CADASTRAL_MUNICIPALITY',
                                    'SETTLEMENT', 'MUNICIPALITY', 'NONE'
                                )),
    geometry_id                 UUID REFERENCES spatial_resolution_geometries(id) ON DELETE RESTRICT,
    confidence_reason           TEXT NOT NULL CHECK (btrim(confidence_reason) <> ''),
    candidate_evidence          JSONB NOT NULL DEFAULT '[]'::jsonb
                                CHECK (jsonb_typeof(candidate_evidence) IN ('array', 'object')),
    member_point_count          BIGINT CHECK (member_point_count IS NULL OR member_point_count > 0),
    resolved_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    cached_at                   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_location_resolution_cache_input UNIQUE (
        resolver, resolver_version, input_fingerprint,
        source_dataset, source_dataset_version, source_dataset_sha256
    ),
    CONSTRAINT ck_location_resolution_cache_result CHECK (
        (
            resolution_status = 'RESOLVED'
            AND geometry_id IS NOT NULL
            AND location_precision <> 'NONE'
        )
        OR (
            resolution_status <> 'RESOLVED'
            AND geometry_id IS NULL
            AND location_precision = 'NONE'
        )
    ),
    CONSTRAINT ck_location_resolution_cache_expiry CHECK (
        expires_at IS NULL OR expires_at > cached_at
    )
);

CREATE TABLE location_resolution_attempts (
    id                          UUID PRIMARY KEY,
    property_reference_id       UUID NOT NULL REFERENCES property_references(id) ON DELETE RESTRICT,
    used_cache_record_id        UUID REFERENCES location_resolution_cache_records(id) ON DELETE RESTRICT,
    resolver                    TEXT NOT NULL CHECK (btrim(resolver) <> ''),
    resolver_version            TEXT NOT NULL CHECK (btrim(resolver_version) <> ''),
    input_fingerprint           CHAR(64) NOT NULL CHECK (input_fingerprint ~ '^[0-9a-f]{64}$'),
    source_dataset              TEXT NOT NULL CHECK (btrim(source_dataset) <> ''),
    source_dataset_version      TEXT NOT NULL CHECK (btrim(source_dataset_version) <> ''),
    source_dataset_sha256       CHAR(64) NOT NULL CHECK (source_dataset_sha256 ~ '^[0-9a-f]{64}$'),
    source_feature_id           TEXT,
    resolution_status           VARCHAR(16) NOT NULL
                                CHECK (resolution_status IN (
                                    'RESOLVED', 'NONE', 'NOT_FOUND', 'AMBIGUOUS', 'INVALID', 'ERROR'
                                )),
    location_precision          VARCHAR(32) NOT NULL
                                CHECK (location_precision IN (
                                    'PARCEL', 'ADDRESS', 'STREET', 'CADASTRAL_MUNICIPALITY',
                                    'SETTLEMENT', 'MUNICIPALITY', 'NONE'
                                )),
    geometry_id                 UUID REFERENCES spatial_resolution_geometries(id) ON DELETE RESTRICT,
    confidence_reason           TEXT NOT NULL CHECK (btrim(confidence_reason) <> ''),
    candidate_evidence          JSONB NOT NULL DEFAULT '[]'::jsonb
                                CHECK (jsonb_typeof(candidate_evidence) IN ('array', 'object')),
    member_point_count          BIGINT CHECK (member_point_count IS NULL OR member_point_count > 0),
    attempted_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at                 TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_location_resolution_attempt_reference UNIQUE (id, property_reference_id),
    CONSTRAINT ck_location_resolution_attempt_time CHECK (completed_at >= attempted_at),
    CONSTRAINT ck_location_resolution_attempt_result CHECK (
        (
            resolution_status = 'RESOLVED'
            AND geometry_id IS NOT NULL
            AND location_precision <> 'NONE'
            AND resolved_at IS NOT NULL
        )
        OR (
            resolution_status = 'NONE'
            AND geometry_id IS NULL
            AND location_precision = 'NONE'
            AND resolved_at IS NOT NULL
        )
        OR (
            resolution_status IN ('NOT_FOUND', 'AMBIGUOUS', 'INVALID', 'ERROR')
            AND geometry_id IS NULL
            AND location_precision = 'NONE'
            AND resolved_at IS NULL
        )
    ),
    CONSTRAINT ck_location_resolution_resolved_time CHECK (
        resolved_at IS NULL OR (resolved_at >= attempted_at AND resolved_at <= completed_at)
    )
);

CREATE INDEX idx_location_resolution_cache_records_geometry
    ON location_resolution_cache_records (geometry_id)
    WHERE geometry_id IS NOT NULL;
CREATE INDEX idx_location_resolution_attempts_reference
    ON location_resolution_attempts (property_reference_id, completed_at DESC, id);
CREATE INDEX idx_location_resolution_attempts_input
    ON location_resolution_attempts (
        property_reference_id, resolver, resolver_version,
        input_fingerprint, source_dataset_version
    );
CREATE INDEX idx_location_resolution_attempts_geometry
    ON location_resolution_attempts (geometry_id)
    WHERE geometry_id IS NOT NULL;
CREATE INDEX idx_location_resolution_attempts_used_cache
    ON location_resolution_attempts (used_cache_record_id)
    WHERE used_cache_record_id IS NOT NULL;

CREATE TABLE current_location_resolutions (
    property_reference_id       UUID PRIMARY KEY REFERENCES property_references(id) ON DELETE RESTRICT,
    resolution_attempt_id       UUID NOT NULL UNIQUE,
    selected_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    selection_reason            TEXT NOT NULL CHECK (btrim(selection_reason) <> ''),
    CONSTRAINT fk_current_location_resolution_attempt
        FOREIGN KEY (resolution_attempt_id, property_reference_id)
        REFERENCES location_resolution_attempts (id, property_reference_id)
        ON DELETE RESTRICT
);

CREATE OR REPLACE FUNCTION reject_location_resolution_attempt_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'location_resolution_attempts is append-only';
END;
$$;

CREATE TRIGGER trg_location_resolution_attempts_append_only
    BEFORE UPDATE OR DELETE ON location_resolution_attempts
    FOR EACH ROW EXECUTE FUNCTION reject_location_resolution_attempt_mutation();

CREATE OR REPLACE FUNCTION validate_current_location_resolution()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    selected_status VARCHAR(16);
BEGIN
    SELECT resolution_status
      INTO selected_status
      FROM location_resolution_attempts
     WHERE id = NEW.resolution_attempt_id
       AND property_reference_id = NEW.property_reference_id;

    IF selected_status IS NULL THEN
        RAISE EXCEPTION 'selected resolution attempt does not belong to property reference';
    END IF;
    IF selected_status NOT IN ('RESOLVED', 'NONE') THEN
        RAISE EXCEPTION 'only RESOLVED or NONE attempts may be selected, got %', selected_status;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_current_location_resolution_valid
    BEFORE INSERT OR UPDATE ON current_location_resolutions
    FOR EACH ROW EXECUTE FUNCTION validate_current_location_resolution();
